### ISSUE TITLE
order_by and order_by_descending without parameter

### ISSUE THREAD

**Issue by scls19fr** [viralogic/py-enumerable#11]
Hello,

`order_by` and `order_by_descending` should works without parameter

```
In [1]: from py_linq import Enumerable
   ...: my_collection = Enumerable([1,2,3])
In [2]: my_collection.order_by_descending().to_list()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-d2a88eb1fd02> in <module>()
----> 1 my_collection.order_by_descending().to_list()

TypeError: order_by_descending() takes exactly 2 arguments (1 given)
In [3]: my_collection.order_by_descending(lambda x: x).to_list()
Out[18]: [3, 2, 1]
```

Maybe an identity function should be defined inside py-enumerable code

https://stackoverflow.com/questions/8748036/is-there-a-builtin-identity-function-in-python

Searching "lambda x: x" into https://github.com/viralogic/py-enumerable/blob/805cae04b575d8ef5cb7b6d13d109ee29dae5e3a/py_linq/py_linq.py
shows that there's 50 occurences of such a function.

Kind regards

**Comment by viralogic** [comment]
@scls19fr 

Thanks for your input.

This is how the .NET OrderBy and OrderByDescending implementations work. As you can see, a lambda function is always necessary. There is no default lambda function that would allow these methods to work without a parameter. In my mind, that really doesn't make any sense unless you are using simple data types such as integers, strings, floats, etc....and for these cases, you can just pass in lambda x: x as the function.

- [OrderBy](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.orderby(v=vs.110).aspx)
- [OrderByDescending](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.orderbydescending(v=vs.110).aspx)

As you can see there are overloaded methods for OrderBy and OrderByDescending that takes in a IComparer object that implements the IComparer interface.

[IComparer Interface](https://msdn.microsoft.com/en-us/library/system.collections.icomparer(v=vs.110).aspx)

We could implement something similar that would then provide nice separation of concerns between the objects in the Enumerable collection and how to sort them.

Is this what you were looking for in terms of an "identity function"? Let me know what you think. I appreciate any feedback.

**Comment by scls19fr** [comment]
> We could implement something similar that would then provide nice separation of concerns between the objects in the Enumerable collection and how to sort them.

Isn't  `__gt__` purpose ?

`identity` function is just the name of `lambda x: x` or

    def identity(x):
        return x

to avoid flake8 warnings

**Comment by viralogic** [comment]
#12 

> Isn't __gt__ purpose ?

Yes the the __gt__ slot could be used for the purpose of providing a method to hook into that would tell Enumerable how the collection is sorted. However, it would force the objects in the collection to be classes where __gt__ is defined and would make the order_by and order_by_descending less flexible, less dynamic,  and less expressive/more hidden to the programmer. If the developer needs to find out how the sort was done, they need to go and look in the implemented class to figure it out instead of just reading it in the sort code. 

For example, say you have a collection of houses:

```
houses = [
    House(address="1600 Pennsylvania Avenue", price=100000000),
    House(address="100 Main Street", price=500000)
]

sorted_houses = Enumerable(houses).order_by()
```
This code would yield what exactly? Are you sorting by address or price? The developer would only know by loading up the House class and inspecting the __gt__, __lt__, __lte__, __gte__, etc slots.

Now, I can see that this "identity" function would work for:

`sorted_house_price = Enumerable(houses).select(lambda x: x.price).order_by()`

but this is not the same as sorting more complex objects and would be the only case where the "identity" function would make sense. And it isn't much harder to write:

`sorted_house_price = Enumerable(houses).select(lambda x: x.price).order_by(lambda x: x)`

and I would even suggest that this statement is more clear to the developer that a simple object (int, string, etc.) is getting sorted - especially in a dynamically typed language like  #Python.

So in my mind, this code change isn't really necessary, and provides little value to the programmer just to remove some Flake 8 warnings. Not really worth the trade off to me.

Appreciate the feedback. I know I may seem like I am being a little stubborn here (which I am absolutely), but I feel pretty strongly about keeping this API clear and expressive. So I won't be merging in this identity function change.
