### ISSUE TITLE
group_by bug

### ISSUE THREAD

**Issue by GF-Huang** [viralogic/py-enumerable#50]
![image](https://user-images.githubusercontent.com/4510984/81631237-fbfe1180-9439-11ea-9ebf-0362c0f4adc3.png)

![image](https://user-images.githubusercontent.com/4510984/81631766-3320f280-943b-11ea-92bc-866c014228a9.png)

**Comment by viralogic** [comment]
Hi @GF-Huang ,

Sorry that your experience with py-linq has been suboptimal. I am finding it hard to understand the context of why you are getting the error you are seeing based on the screenshots you submitted. Can you provide a little more information or a snippet of code that illustrates the bug you are encountering?

Unrelated to your error, it appears you are trying to group influxdb records by a field. Typically it is better to that within the database itself rather than pull records from the database first and then use a library like py-linq to do it. Maybe you could alter your code to [group](https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/group/) within influxdb instead?

Thanks for using py-linq.

Bruce

**Comment by GF-Huang** [comment]
The `get_field()` method will return either `a_change` or `b_change` (in this case is volume_change), I want to group them into two groups with key `a_change` and `b_change`, but the result use the first character of the string as key.

**Comment by viralogic** [comment]
@GF-Huang 
Thanks for extra information. I have replicated the issue. I will post a fix as soon as I can.

**Comment by viralogic** [comment]
Patch is out

`pip install --upgrade py-linq`
