### ISSUE TITLE
Provide some simple examples

### ISSUE THREAD

**Issue by scls19fr** [viralogic/py-enumerable#6]
This one (inspired by [asq](https://github.com/sixty-north/asq/))

```python
In [1]: from py_linq import Enumerable

In [2]: a = [1, 2, 3, 4, 5, 6]

In [3]: res = Enumerable(a).where(lambda x: x>2)

In [4]: list(res)
[3, 4, 5, 6]

In [5]: res.count()
Out[5]: 4
```

**Comment by scls19fr** [comment]
A good point is that py-enumerable doesn't have same issue than asq
`https://github.com/sixty-north/asq/issues/5`

**Comment by scls19fr** [comment]
asq also provide this example

```python
>>> from asq.initiators import query
>>> words = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
>>> query(words).order_by(len).then_by().take(5).select(str.upper).to_list()
['ONE', 'SIX', 'TEN', 'TWO', 'FIVE']
```

but with `py-enumerable` there is no `then_by` method
so

```python
In [10]: words = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
In [11]: Enumerable(words).order_by(len).take(5).select(str.upper).to_list()
Out[11]: ['ONE', 'TWO', 'SIX', 'TEN', 'ZERO']
```

doesn't return same result.

**Comment by viralogic** [comment]
Correct. Then by is not implemented in py_linq.

You are also correct that py_linq doesn't return the same result as asq here, but it is not clear to me that it is because it is missing the then_by() implementation. It is hard to tell because there are no arguments to the then_by() method in the asq example. So what it is the key for the secondary sort?

As you can see by the result returned by py_linq is still correct. The ordering is just different from asq.

**Comment by scls19fr** [comment]
Maybe @rob-smallshire can explain us what is the key for the secondary sort?

**Comment by viralogic** [comment]
![image](https://user-images.githubusercontent.com/10284720/28040980-e601302e-6584-11e7-97cb-4b6d0aa01e6a.png)

Looks like it is just alphabetic sorting after sorting by string length

**Comment by viralogic** [comment]
Created 2 new separate issues. Will close this one.
